version: "3.7"

services:
  webapp:
    build: 
      context: ./webapp
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_INTERNAL=http://server:8080
        - VITE_BRANDING=Noteshare.space [preview]
    ports:
      - "3000:3000"
  
  migrate:
    build:
      context: ./server/prisma
      dockerfile: Dockerfile
    volumes:
      - sqlite:/database/
    environment:
      - DATABASE_URL=file:/database/db.sqlite
  
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - sqlite:/database/
    environment:
      - DATABASE_URL=file:/database/db.sqlite
      - FRONTEND_URL=http://localhost:3000
      - CLEANUP_INTERVAL_SECONDS=600
      - POST_LIMIT_WINDOW_SECONDS=86400
      - POST_LIMIT=50
    depends_on:
      - migrate

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  sqlite: